app:
  port: 4000

db:
  driver: "mysql"
  host: "192.168.1.152"
  port: 3306
  username: "parktify"
  password: "1234"
  database: "parktify"

cloudinary:
  name: "dvzib8cte"
  apiKey: 192494392215866
  apiSecret: "5uGKxDU0UWmbCtKs7hAS_YzrByY"
  folder: "Parktify"
