version: '3.8'

services:

  # Application
  server: 
    # depends_on:
    #   - mysql
    #   - redis
    container_name: parktify-server
    build: .
    ports:
      - 4000:4000
    expose:
      - 4000

  # Database
  # mysql:
  #   image: mysql:latest
  #   container_name: parktify-mysql
  #   restart: always
  #   environment: 
  #     MYSQL_DATABASE: 'parktify'
  #     MYSQL_USER: 'parktify'
  #     MYSQL_PASSWORD: '1234'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports: 
  #     - 3306:3306
  #   expose: 
  #     - 3306
  #   volumes: 
  #     - ./data:/var/lib/mysql

  # Cache in memory
  # redis:
  #   image: redis:latest
  #   container_name: parktify-redis
  #   restart: always
  #   ports: 
  #     - 1234:6379
  #   expose:
  #     - 1234
  
volumes:
  db_data: 