name: deploy app

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker compose
        run: docker-compose -f "docker-compose.yml" up -d --build
