name: deploy app

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on:
      - self-hosted
      - test

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker version
        run: docker -v

      - name: run docker compose
        run: docker-compose -f "docker-compose.yml" up -d --build

      # - name: run
      #   run: go run main.go
