name: deploy app

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    timeout-minutes: 2
    runs-on:
      - self-hosted
      - test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: docker version
        run: docker -v

      # - name: docker compose
      #   uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "./docker-compose.yml"

      - name: docker build
        run: |
          docker build . -t parktify-api:latest

      # - name: docker build
      #   run: |
      #     docker build . --file Dockerfile --tag parktify-api:$(date +%s)

      # - name: run docker compose
      #   run: docker-compose -f "docker-compose.yml" up -d --build

      # - name: run
      #   run: go run main.go
